server:
  port: 8080
  servlet:
    context-path: /api
spring:
    datasource:
      url: "jdbc:mysql://localhost:3306/coach_company"
      username: root
      password: root
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true